### ISSUE TITLE
Support for OpenJDK 17 LTS SDK extension

### ISSUE THREAD

**Issue by webagentur-hartmann** [flathub/de.willuhn.Jameica#14]
Since version 2.10.2 Jameica supports Java versions greater than version 18. So, it seems to be possible to raise the integrated SDK extension to OpenJDK 17 LTS.

**Comment by tobias-hammerschmidt** [comment]
Fixed in https://github.com/flathub/de.willuhn.Jameica/commit/29c67353db9b5156c8b243bbee406cd159ddecf3.
