### ISSUE TITLE
The GNOME 42 runtime is no longer supported as of March 21, 2023 (de.willuhn.Jameica)

### ISSUE THREAD

**Issue by PCCounselor** [flathub/de.willuhn.Jameica#26]
I have a problem with the Linux (flatpak) on my Linux-Mint-PC:

sudo flatpak update --system
Looking for updates…
Info: org.gnome.Platform//42 is end-of-life, with reason:
   The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   de.willuhn.Jameica 

Is there any Update?

**Comment by hanny00** [comment]
I have the info too if i update my flatpaks

**Comment by tobias-hammerschmidt** [comment]
There was an issue with the scripting plugin and Gnome 42 platform (see #21). With the recent update of Jameica to 2.10.4 we might check again with a more recent Gnome platform like 43 or 44.

**Comment by tobias-hammerschmidt** [comment]
I've just updated the beta branch to gnome platform 44. You could add the flathub beta repository and give it a try (see https://discourse.flathub.org/t/how-to-use-flathub-beta/2111). Before pushing this to master I would like to ensure that the scripting plugin is not broken again. @Braintoe maybe you could also give this build a try?

**Comment by hanny00** [comment]
OH thank you, i will jump over to the beta and have a look for you

**Comment by Braintoe** [comment]
> I've just updated the beta branch to gnome platform 44. You could add the flathub beta repository and give it a try (see https://discourse.flathub.org/t/how-to-use-flathub-beta/2111). Before pushing this to master I would like to ensure that the scripting plugin is not broken again. @Braintoe maybe you could also give this build a try?

Among lots of Gtk warnings I get a couple of these, not sure if they are important...
`(Jameica 2.10.4:2): Gtk-CRITICAL **: 18:37:57.872: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar`

... but apart from that the plugin works as intended!

**Comment by tobias-hammerschmidt** [comment]
@Braintoe thanks for testing. The warnings don't look important to me so I'll merge the platform update into the master branch.
