### ISSUE TITLE
 The GNOME 44 runtime is no longer supported as of March 20, 2024 Flatpak Version 

### ISSUE THREAD

**Issue by hanny00** [flathub/de.willuhn.Jameica#34]
Info: runtime org.gnome.Platform branch 44 is end-of-life, with reason:
   The GNOME 44 runtime is no longer supported as of March 20, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   de.willuhn.Jameica

**Comment by tobias-hammerschmidt** [comment]
Fixed with https://github.com/flathub/de.willuhn.Jameica/pull/35
